.TH DIS6502 1 "12 SEP 2003"
.UC 4
.SH NAME
dis6502 \- Disassemble 6502 object code
.SH SYNOPSIS
.I dis6502
[
.I \-b 
]
[
.I -p \fIpfile\fP 
]
.I file
.LP
.SH DESCRIPTION
.I  Dis6502
disassembles 6502 binary files.  Binary formats understood include
raw binary files, Atari boot and load files, and Commodore 64 files.
Equate and control files can be included via the
.I -p
option to name well known locations and to control the disassembly
process.  The output includes a cross reference.
.PP
The disassembly process is a two pass operation:  First the program
flow is traced starting with the init and run parameters in the file
headers.  The dump routine then prints out the information.
.PP
The command line options are:
.TP
.I \-r \fIaddress\fP
Raw binary input file, with the first byte of the file being associated with
the specified address.
.TP
.I \-b
Atari boot format input file.
.TP
.I \-l
Atari load format input file.
.TP
.I \-c
Commodore format input file.
.TP
.I \-p \fIpfile\fP 
Read in the predefine file \fIpfile\fP.
Up to 20 \fI-p\fP options may be included.
.TP
.I \-v \fIaddress\fP
Use an alternate address for the reset and interrupt vectors.
.TP
.I \-7
Mask off MSB of character data.
.PP
Lines in pfile consist of:
.PP
name .eq address
.PP
 .stop address
.PP
 .trace address
.PP 
.I Address 
may be a decimal number or
may be a hexadecimal number (the first character of the number
should be "$").  For example, "$21b5" is
the hexadecimal number 21b5.
.I Name
is a sequence of numbers and characters starting with a
letter.
.I .trace 
causes
the trace process to continue at the address given.  
.I .stop
causes the
trace process to stop at the address given.
.SH AUTHORS
Robert Bond, Udi Finkelstein, and Eric Smith
.SH BUGS
